<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net472;net461</TargetFrameworks>
    <GeneratePackageOnBuild Condition="$(Configuration) == 'Release' ">true</GeneratePackageOnBuild>
    <!--<GeneratePackageOnBuild>true</GeneratePackageOnBuild>-->
    <!-- <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput> -->
    <LibTargetFrameworks>netstandard2.0;net472;net461</LibTargetFrameworks>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb;.xml</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <PackageId>IppDotNetSdkForQuickBooksApiV3</PackageId>
    <AssemblyName>IppDotNetSdkForQuickBooksApiV3</AssemblyName>
    <DocumentationFile>$(BaseOutputPath)$(AssemblyName).xml</DocumentationFile>
    <PackageVersionSuffix>pre</PackageVersionSuffix>
    <Version>$(MainVersion)-$(PackageVersionSuffix)</Version>
    <Version>$(MainVersion)</Version>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <!--<NoBuild>true</NoBuild>-->
    <!-- <IncludeBuildOutput>true</IncludeBuildOutput> -->
    <AutoGenerateBindingRedirects>False</AutoGenerateBindingRedirects>
    <Description>The IPP .NET SDK for QuickBooks V3 is a set of .NET classes that make it easier to call QuickBooks APIs. This is the .Net Standard 2.0 version of the .Net SDK</Description>
    <Authors>Intuit</Authors>
    <RepositoryUrl>https://github.com/intuit/QuickBooks-V3-DotNET-SDK</RepositoryUrl>
	<PackageIcon>logo.png</PackageIcon>  
    <PackageProjectUrl>https://developer.intuit.com/app/developer/qbo/docs/develop/sdks-and-samples-collections/net</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>https://github.com/intuit/QuickBooks-V3-DotNET-SDK/releases</PackageReleaseNotes>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\Tools\XsdExtension\Intuit.Ipp.Data\Intuit.Ipp.Data.csproj" />
    <ProjectReference Include="..\Intuit.Ipp.Core\Intuit.Ipp.Core.csproj" />
    <ProjectReference Include="..\Intuit.Ipp.DataService\Intuit.Ipp.DataService.csproj" />
    <ProjectReference Include="..\Intuit.Ipp.Diagnostics\Intuit.Ipp.Diagnostics.csproj" />
    <ProjectReference Include="..\Intuit.Ipp.EntitlementService\Intuit.Ipp.EntitlementService.csproj" />
    <ProjectReference Include="..\Intuit.Ipp.Exception\Intuit.Ipp.Exception.csproj" />
    <ProjectReference Include="..\Intuit.Ipp.GlobalTaxService\Intuit.Ipp.GlobalTaxService.csproj" />
    <ProjectReference Include="..\Intuit.Ipp.OAuth2PlatformClient\Intuit.Ipp.OAuth2PlatformClient.csproj" />
    <ProjectReference Include="..\Intuit.Ipp.OAuth2PlatformClient.Diagnostics\Intuit.Ipp.OAuth2PlatformClient.Diagnostics.csproj" />
    <ProjectReference Include="..\Intuit.Ipp.QueryFilter\Intuit.Ipp.QueryFilter.csproj" />
    <ProjectReference Include="..\Intuit.Ipp.ReportService\Intuit.Ipp.ReportService.csproj" />
    <ProjectReference Include="..\Intuit.Ipp.Retry\Intuit.Ipp.Retry.csproj" />
    <ProjectReference Include="..\Intuit.Ipp.Security\Intuit.Ipp.Security.csproj" />
    <ProjectReference Include="..\Intuit.Ipp.Utility\Intuit.Ipp.Utility.csproj" />
    <ProjectReference Include="..\Intuit.Ipp.WebHooksService\Intuit.Ipp.WebHooksService.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="logo.png" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
